name: Question or Support
description: Ask a question or get help using mcp-delegator
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Ask your question below and we'll do our best to assist!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic Area
      description: What is your question about?
      options:
        - Installation & Setup
        - Local CLI Usage
        - Local SDK Usage
        - Cloud Execution
        - Task Management
        - Configuration
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your setup or what you're trying to achieve
      placeholder: I'm trying to... and I've already tried...

  - type: textarea
    id: config
    attributes:
      label: Configuration (if relevant)
      description: Share your relevant MCP configuration or setup
      render: json
      placeholder: |
        {
          "mcpServers": {
            "mcp-delegator": {
              "command": "npx",
              "args": ["-y", "@littlebearapps/mcp-delegator"]
            }
          }
        }

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of mcp-delegator are you using?
      placeholder: e.g., 3.2.1

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Anything else we should know?
      placeholder: Any other details?
